DATABASE:
  ENDPOINT_URL:
    dev: null
    prod: null
    local: null
  NAME:
    dev: mlogDB
    prod: mlogDB
    local: mlogDB
  USERNAME:
    dev: ssafy
    prod: ssafy
    local: ssafy
  PASSWORD:
    dev: ssafy
    prod: ssafy
    local: ssafy
JWT:
  SECRET: TKvlchlrhdlqslekwlsWkrleogowntpdy