spring:
  config:
    import: application-secret.yml
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DATABASE.NAME.local}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DATABASE.USERNAME.local}
    password: ${DATABASE.PASSWORD.local}
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: ${MAIL.USERNAME}
    password: ${MAIL.PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
          enable: true

mail:
  root: ${MAIL.ROOT.local}
  sender-email: ${MAIL.USERNAME}

jwt:
  token:
    header: X-MLOG-AUTH
    issuer: mlog
    client-secret: ${JWT.SECRET}
    expiry-seconds: 10000